/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Samantha
 */
public class mainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainWindow.class.getName());

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Simulador = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        secc1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        create = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        ciclosSatisfacerE_label = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        InstLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        ciclosparaE_label = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        Instrucciones_Input1 = new javax.swing.JSpinner();
        Instrucciones_Input2 = new javax.swing.JSpinner();
        ciclosparaE_label3 = new javax.swing.JLabel();
        ciclosparaE_label4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Instrucciones_Input3 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        ciclosparaE_label6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        planificacion_input = new javax.swing.JComboBox<>();
        ciclosparaE_label5 = new javax.swing.JLabel();
        guardarPlanning1 = new javax.swing.JButton();
        ciclosparaE_label8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ciclosparaE_label1 = new javax.swing.JLabel();
        ciclosparaE_label2 = new javax.swing.JLabel();
        duracionCiclo_input = new javax.swing.JSpinner();
        duracionCiclo_reset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ColaListos = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ColaBloqueados = new java.awt.ScrollPane();
        ColaSusp_block = new java.awt.ScrollPane();
        ColaSusp_Listos = new java.awt.ScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        metrics = new javax.swing.JPanel();
        logs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 595));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CPU");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 60));

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        secc1.setBackground(new java.awt.Color(0, 153, 153));
        secc1.setPreferredSize(new java.awt.Dimension(260, 595));
        secc1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel3.setPreferredSize(new java.awt.Dimension(260, 275));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CREAR PROCESO");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setInheritsPopupMenu(false);
        jPanel3.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(260, 35));

        create.setBackground(new java.awt.Color(204, 204, 204));
        create.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        create.setForeground(new java.awt.Color(0, 0, 0));
        create.setText("Crear");
        create.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        create.setPreferredSize(new java.awt.Dimension(95, 23));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel6.add(create);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ciclosSatisfacerE_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ciclosSatisfacerE_label.setForeground(new java.awt.Color(255, 255, 255));
        ciclosSatisfacerE_label.setText("Ciclos para Satisfacer ");
        jPanel7.add(ciclosSatisfacerE_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombre:");
        jPanel7.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        InstLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InstLabel.setForeground(new java.awt.Color(255, 255, 255));
        InstLabel.setText("Cant. Instrucciones");
        jPanel7.add(InstLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        tipoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipoLabel.setText("Tipo");
        jPanel7.add(tipoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        ciclosparaE_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ciclosparaE_label.setForeground(new java.awt.Color(255, 255, 255));
        ciclosparaE_label.setText("Excepcion");
        jPanel7.add(ciclosparaE_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        NameInput.setBackground(new java.awt.Color(51, 51, 51));
        NameInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NameInput.setPreferredSize(new java.awt.Dimension(68, 24));
        jPanel7.add(NameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, -1));

        Instrucciones_Input1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Instrucciones_Input1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9999, 1));
        jPanel7.add(Instrucciones_Input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        Instrucciones_Input2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Instrucciones_Input2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9999, 1));
        jPanel7.add(Instrucciones_Input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        ciclosparaE_label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ciclosparaE_label3.setForeground(new java.awt.Color(255, 255, 255));
        ciclosparaE_label3.setText("Ciclos para la ");
        jPanel7.add(ciclosparaE_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        ciclosparaE_label4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ciclosparaE_label4.setForeground(new java.awt.Color(255, 255, 255));
        ciclosparaE_label4.setText("Excepcion");
        jPanel7.add(ciclosparaE_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU bound", "I/O bound", " " }));
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        Instrucciones_Input3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Instrucciones_Input3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9999, 1));
        jPanel7.add(Instrucciones_Input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        secc1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(260, 170));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ciclosparaE_label6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ciclosparaE_label6.setForeground(new java.awt.Color(0, 0, 0));
        ciclosparaE_label6.setText("RELOG GLOBAL");
        jPanel5.add(ciclosparaE_label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        secc1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel10.setPreferredSize(new java.awt.Dimension(135, 175));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        planificacion_input.setBackground(new java.awt.Color(0, 0, 0));
        planificacion_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Round Robin", "FCFS", "FIFO", "Item 4" }));
        jPanel10.add(planificacion_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        ciclosparaE_label5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ciclosparaE_label5.setForeground(new java.awt.Color(0, 0, 0));
        ciclosparaE_label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciclosparaE_label5.setText("Politica de ");
        ciclosparaE_label5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(ciclosparaE_label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        guardarPlanning1.setBackground(new java.awt.Color(204, 204, 204));
        guardarPlanning1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarPlanning1.setForeground(new java.awt.Color(0, 0, 0));
        guardarPlanning1.setText("Guardar ");
        guardarPlanning1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        guardarPlanning1.setPreferredSize(new java.awt.Dimension(95, 23));
        guardarPlanning1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPlanning1ActionPerformed(evt);
            }
        });
        jPanel10.add(guardarPlanning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        ciclosparaE_label8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ciclosparaE_label8.setForeground(new java.awt.Color(0, 0, 0));
        ciclosparaE_label8.setText("Planificacion");
        jPanel10.add(ciclosparaE_label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel9.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ciclosparaE_label1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ciclosparaE_label1.setForeground(new java.awt.Color(0, 0, 0));
        ciclosparaE_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciclosparaE_label1.setText(" Duracion del");
        ciclosparaE_label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(ciclosparaE_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        ciclosparaE_label2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ciclosparaE_label2.setForeground(new java.awt.Color(0, 0, 0));
        ciclosparaE_label2.setText("ciclo");
        jPanel8.add(ciclosparaE_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        duracionCiclo_input.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        duracionCiclo_input.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9999, 1));
        jPanel8.add(duracionCiclo_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        duracionCiclo_reset.setBackground(new java.awt.Color(204, 204, 204));
        duracionCiclo_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        duracionCiclo_reset.setForeground(new java.awt.Color(0, 0, 0));
        duracionCiclo_reset.setText("Reset");
        duracionCiclo_reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        duracionCiclo_reset.setPreferredSize(new java.awt.Dimension(95, 23));
        duracionCiclo_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionCiclo_resetActionPerformed(evt);
            }
        });
        jPanel8.add(duracionCiclo_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        jPanel9.add(jPanel8, java.awt.BorderLayout.CENTER);

        secc1.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(secc1, java.awt.BorderLayout.LINE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        ColaListos.add(jScrollPane2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ColaListos.add(jScrollPane1);

        jPanel4.add(ColaListos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 920, 160));
        jPanel4.add(ColaBloqueados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 920, 170));
        jPanel4.add(ColaSusp_block, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 920, 170));
        jPanel4.add(ColaSusp_Listos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 920, 170));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel7.setText("COLA SUSPENDIDOS/LISTOS");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 200, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel4.setText("COLA LISTOS");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel5.setText("COLA BLOQUEADOS");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel6.setText("COLA SUSPENDIDOS/BLOQUEADO");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, 20));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout SimuladorLayout = new javax.swing.GroupLayout(Simulador);
        Simulador.setLayout(SimuladorLayout);
        SimuladorLayout.setHorizontalGroup(
            SimuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1522, Short.MAX_VALUE)
        );
        SimuladorLayout.setVerticalGroup(
            SimuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Simulador", Simulador);

        javax.swing.GroupLayout metricsLayout = new javax.swing.GroupLayout(metrics);
        metrics.setLayout(metricsLayout);
        metricsLayout.setHorizontalGroup(
            metricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1522, Short.MAX_VALUE)
        );
        metricsLayout.setVerticalGroup(
            metricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gráficas y Métricas", metrics);

        javax.swing.GroupLayout logsLayout = new javax.swing.GroupLayout(logs);
        logs.setLayout(logsLayout);
        logsLayout.setHorizontalGroup(
            logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1522, Short.MAX_VALUE)
        );
        logsLayout.setVerticalGroup(
            logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("logs", logs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void duracionCiclo_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionCiclo_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionCiclo_resetActionPerformed

    private void guardarPlanning1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPlanning1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarPlanning1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.ScrollPane ColaBloqueados;
    private java.awt.ScrollPane ColaListos;
    private java.awt.ScrollPane ColaSusp_Listos;
    private java.awt.ScrollPane ColaSusp_block;
    private javax.swing.JLabel InstLabel;
    private javax.swing.JSpinner Instrucciones_Input1;
    private javax.swing.JSpinner Instrucciones_Input2;
    private javax.swing.JSpinner Instrucciones_Input3;
    private javax.swing.JTextField NameInput;
    private javax.swing.JPanel Simulador;
    private javax.swing.JLabel ciclosSatisfacerE_label;
    private javax.swing.JLabel ciclosparaE_label;
    private javax.swing.JLabel ciclosparaE_label1;
    private javax.swing.JLabel ciclosparaE_label2;
    private javax.swing.JLabel ciclosparaE_label3;
    private javax.swing.JLabel ciclosparaE_label4;
    private javax.swing.JLabel ciclosparaE_label5;
    private javax.swing.JLabel ciclosparaE_label6;
    private javax.swing.JLabel ciclosparaE_label8;
    private javax.swing.JButton create;
    private javax.swing.JSpinner duracionCiclo_input;
    private javax.swing.JButton duracionCiclo_reset;
    private javax.swing.JButton guardarPlanning1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel logs;
    private javax.swing.JPanel metrics;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JComboBox<String> planificacion_input;
    private javax.swing.JPanel secc1;
    private javax.swing.JLabel tipoLabel;
    // End of variables declaration//GEN-END:variables
}
