package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import model.Proceso;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Samantha
 */
public class ProcessCard extends javax.swing.JPanel {
    private JLabel idLabel;
    private JLabel nameLabel; // Nuevo para el nombre del proceso
    private JLabel pcLabel;
    private JLabel marLabel;
    private JLabel statusLabel;
    private JLabel typeLabel;
    
       private JLabel idValueLabel;
        private JLabel nameValueLabel;
        private JLabel pcValueLabel;
        private JLabel marValueLabel;
        private JLabel statusValueLabel;
        private JLabel typeValueLabel;
    /**
     * Creates new form ProcessCard
     */
    public ProcessCard(Proceso proceso) {

        
     
        setBorder(BorderFactory.createLineBorder(Color.WHITE, 2)); 
        setBackground(Color.DARK_GRAY); 
        setLayout(new GridLayout(6, 2)); // (etiqueta: valor)
        setPreferredSize(new Dimension(200, 120)); 
        setMaximumSize(new Dimension(250, 120)); 
        
         idLabel = new JLabel("ID:");
        nameLabel = new JLabel("Nombre:");
        pcLabel = new JLabel("PC:");
        marLabel = new JLabel("MAR:");
        statusLabel = new JLabel("Status:");
        typeLabel = new JLabel("Tipo:");
        
        applyStyles(idLabel);
        applyStyles(nameLabel);
        applyStyles(pcLabel);
        applyStyles(marLabel);
        applyStyles(statusLabel);
        applyStyles(typeLabel);
        
        
        idValueLabel = new JLabel(String.valueOf(proceso.getId()));
        nameValueLabel = new JLabel(proceso.getName());
        pcValueLabel = new JLabel(String.valueOf(proceso.getPC()));
        marValueLabel = new JLabel(String.valueOf(proceso.getMar()));
        statusValueLabel = new JLabel(proceso.getProcessState().toString());
        typeValueLabel = new JLabel(proceso.isCPUbound() ? "CPU bound" : "I/O bound");
        
        applyStyles(idValueLabel); 
        applyStyles(nameValueLabel);
        applyStyles(pcValueLabel);
        applyStyles(marValueLabel);
        applyStyles(statusValueLabel);
        applyStyles(typeValueLabel);
        
        add(idLabel);
        add(idValueLabel); 
    
        add(nameLabel);
        add(nameValueLabel); 
    
       add(pcLabel);
        add(pcValueLabel);
    
        add(marLabel);
        add(marValueLabel); 
    
        add(statusLabel);
        add(statusValueLabel); 
    
        add(typeLabel);
        add(typeValueLabel);
       
    }
    
    public void updateProcessData(Proceso proceso) {
        
        pcValueLabel.setText(String.valueOf(proceso.getPC()));
        marValueLabel.setText(String.valueOf(proceso.getMar()));
        statusValueLabel.setText(proceso.getProcessState().toString());
    }
    
    private void applyStyles(JLabel label) {
        label.setForeground(Color.WHITE);
        Font currentFont = label.getFont();
        label.setFont(currentFont.deriveFont(Font.BOLD));
        label.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
